#!/bin/bash

cd Adafruit-Libraries
sudo mv Adafruit* /usr/lib/python2.7/
cd ..

if [ ! -d /usr/bin/rpi-clock ]
then
  sudo mkdir /usr/bin/rpi-clock/
fi

sudo mv clock* /usr/bin/rpi-clock/
sudo mv display_test.py /usr/bin/rpi-clock
sudo mv clear_display.py /usr/bin/rpi-clock
sudo mv README /usr/bin/rpi-clock
mv watchdog.sh ~/
cd ~/
sudo chmod +x watchdog.sh
rm -f -r rpi-clock

exit 0
